### PR TITLE
Add basic imenu support over the rule names.

### PR DESCRIPTION
**Pull request by vellvisher**
Co-authored-by: xenodium <alvaro@xenodium.com>

### CODE REVIEW

**Review by codesuki — COMMENTED** [review]
Thanks for the PR! I'll have a look once I am back at work.

**Comment by vellvisher** [comment]
Polite ping - hey @codesuki, did you get time to review the pull request?

**Comment by codesuki** [comment]
Thanks for the ping. Totally forgot. Will have a look today!

**Review by codesuki — APPROVED** [review]
I read up on imenu. Thanks! Learned something new. Seems this should work.

**Comment by xenodium** [comment]
Thanks @vellvisher!

**Pull request merged**
